home/urls.py
from django.urls import path
from .views import HomeView, AboutUsView, ContactUsView, ChefUsView, GalleryView, EventsView

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('contact-us/', ContactUsView.as_view(), name='contact_us'),
    path('our-chefs/', ChefUsView.as_view(), name='our_chefs'),
    path('galleries/', GalleryView.as_view(), name='galleries'),
    path('our-events/', EventsView.as_view(), name='our_events'),

]

mysticcloud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('users.urls', namespace='users')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
    path("change-password/", auth_views.PasswordChangeView.as_view()),
    path("reset-password/", auth_views.PasswordResetView.as_view(), name="reset_password"),
    path("password-reset-done/", auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from .views import MakeReservationView, cancel_reservation, AllReservationsView

app_name = "reservation"

urlpatterns = [
    path('reservation/', MakeReservationView.as_view(), name='reservation'),
    path('view-reservations/', AllReservationsView.as_view(), name='view_reservations'),
    path('cancel-reservation/<int:reservation_id>/', cancel_reservation, name='cancel_reservation'),
]

reservation/models.py
from django.db import models
from users.models import User


class Table(models.Model):
    table_number = models.IntegerField(unique=True)
    capacity = models.IntegerField()

    def __str__(self):
        return f"Table {self.table_number} - Capacity: {self.capacity}"


class Reservation(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    phone = models.IntegerField()
    number_of_persons = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservations')
    table = models.ForeignKey(Table, on_delete=models.CASCADE, related_name='reserved_table')
    start_date = models.DateTimeField()
    end_time = models.DateTimeField()

    def cancel_reservation(self):
        self.delete()

    def __str__(self):
        return f"{self.name} {self.start_date}"

reservation/forms.py
from django import forms
from .models import Reservation, Table


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['name', 'email', 'phone', 'number_of_persons', 'start_date', 'end_time', 'table']
        widgets = {
            "start_date": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "end_time": forms.DateTimeInput({"type": "datetime-local"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['table'].queryset = Table.objects.all()

reservation/views.py
from django.views.generic import CreateView, ListView
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import ReservationForm
from .models import Reservation, Table


class MakeReservationView(CreateView):
    model = Reservation
    form_class = ReservationForm
    template_name = 'reservation/reservation.html'
    success_url = reverse_lazy('home:home')

    def form_valid(self, form):
        reservation = form.save(commit=False)
        reservation.user = self.request.user

        conflicting_reservations = Reservation.objects.filter(
            table=reservation.table,
            start_date__lt=reservation.end_time,
            end_time__gt=reservation.start_date,
        )

        if conflicting_reservations.exists():
            messages.error(self.request, "Table is not available during the specified time range.")
            return render(self.request, 'reservation/reservation.html', {'form': form, 'tables': Table.objects.all()})
        elif reservation.number_of_persons > reservation.table.capacity:
            messages.error(self.request, "This table's capacity is less than the number of persons.")
            return render(self.request, 'reservation/reservation.html', {'form': form, 'tables': Table.objects.all()})
        else:
            reservation.save()
            messages.success(self.request, "Your table reserved successfully!")
            return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Invalid form submission. Please check the form.")
        return render(self.request, 'reservation/reservation.html', {'form': form, 'tables': Table.objects.all()})


class AllReservationsView(ListView):
    model = Reservation
    template_name = 'reservation/view_reservations.html'
    context_object_name = 'user_reservations'

    def get_queryset(self):
        return Reservation.objects.filter(user=self.request.user)


@login_required
def cancel_reservation(request, reservation_id):
    reservation = Reservation.objects.get(pk=reservation_id)
    if request.user == reservation.user:
        reservation.delete()
        messages.success(request, "Your reservation delete !")
        return redirect("reservation:view_reservations")
    return render(request, 'reservation/reservation')

templates/reservation/reservation.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
<h1>Reservation</h1>
{% if not request.user.is_authenticated %}
<h2>if you want to reserve a table, please register /login account before that</h2>
{% else %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Reserve</button>
</form>
{% endif %}
    </div>

{% endblock %}

templates/reservation/view_reservations.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
  <h2>Your Reservations</h2>
  <ul>
    {% for reservation in user_reservations %}
      <li>
        {{ reservation.reserved_tabel.table_number }} {{ reservation.start_date }}
        {% if not reservation.is_cancelled %}
          - <a href="{% url 'reservation:cancel_reservation' reservation.id %}">Cancel</a>
        {% else %}
          - Canceled
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/reservation/view_resrvations.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
  <h2>Your Reservations</h2>
  <ul>
    {% for reservation in user_reservations %}
      <li>
        {{ reservation.reserved_tabel.table_number }} {{ reservation.start_date }}
        {% if not reservation.is_cancelled %}
          - <a href="{% url 'reservation:cancel_reservation' reservation.id %}">Cancel</a>
        {% else %}
          - Canceled
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock %}