home/urls.py
from django.urls import path
from .views import HomeView, AboutUsView, ContactUsView, ChefUsView, GalleryView, EventsView

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('contact-us/', ContactUsView.as_view(), name='contact_us'),
    path('our-chefs/', ChefUsView.as_view(), name='our_chefs'),
    path('galleries/', GalleryView.as_view(), name='galleries'),
    path('our-events/', EventsView.as_view(), name='our_events'),

]

menu/urls.py
from django.urls import path
from .views import MenuListView, BarListView, HookahListView, BarCategoryDetailView

app_name = 'menu'

urlpatterns = [
    path("", MenuListView.as_view(), name="menu_items"),
    path("bar-items/", BarListView.as_view(), name="bar_items"),
    path("hookahs/", HookahListView.as_view(), name="hookahs"),
    path('bar-items/<int:pk>/', BarCategoryDetailView.as_view(), name='bar_item_detail'),
]

mysticcloud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('users.urls', namespace='users')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
    path("change-password/", auth_views.PasswordChangeView.as_view()),
    path("reset-password/", auth_views.PasswordResetView.as_view(), name="reset_password"),
    path("password-reset-done/", auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from .views import MakeReservationView, cancel_reservation, AllReservationsView

app_name = "reservation"

urlpatterns = [
    path('reservation/', MakeReservationView.as_view(), name='reservation'),
    path('view-reservations/', AllReservationsView.as_view(), name='view_reservations'),
    path('cancel-reservation/<int:reservation_id>/', cancel_reservation, name='cancel_reservation'),
]

users/urls.py
from django.urls import path
from .views import LoginView, RegistrationView, ValidateUserLink, LogoutView, UserUpdate, UserProfile

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("<int:pk>/<str:token>/", ValidateUserLink.as_view(), name="verify"),
    path("update-user/<int:pk>/", UserUpdate.as_view(), name="update_user"),
    path('users/detail/<int:pk>/', UserProfile.as_view(), name='user_profile'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>MysticCloud Lounge </title>
    <meta content="" name="description">
    <meta content="" name="keywords">

<!--     Favicons-->
        <link href="{% static 'img/favicon.png' %}" rel="icon">
        <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

</head>

<body>

<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

        <a href="{% url 'home:home' %}" class="logo d-flex align-items-center me-auto me-lg-0">
            <!-- Uncomment the line below if you also wish to use an image logo -->
            <!-- <img src="static/img/logo.png" alt=""> -->
            <h1>MysticCloud Lounge</h1>
        </a>

        <nav id="navbar" class="navbar">
            <ul>
                <li><a href="{% url 'home:home' %}">Home</a></li>
                <li><a href="{% url 'menu:menu_items' %}">Menu</a></li>
                <li><a href="{% url 'menu:hookahs' %}">Hookah</a></li>
                <li><a href="{% url 'home:our_events' %}">Events</a></li>
                <li><a href="{% url 'home:our_chefs' %}">Chefs</a></li>
                <li><a href="{% url 'home:about_us' %}">About</a></li>
                <li><a href="{% url 'home:galleries' %}">Gallery</a></li>
                <li class="dropdown"><a href="#"><span>User</span> <i
                        class="bi bi-chevron-down dropdown-indicator"></i></a>
                    <ul>

                        {% if not request.user.is_authenticated %}
                        <li><a href="{% url 'users:registration' %}">Register</a></li>
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                        {% else %}
                        <li><a href="{% url 'users:user_profile' request.user.id %}">Profile</a></li>
                        <li><a href="{% url  'users:logout' %}">LogOut</a></li>
                        {% endif %}


                    </ul>
                </li>
                <li><a href="{% url 'home:contact_us' %}">Contact</a></li>
            </ul>
        </nav><!-- .navbar -->

        <a class="btn-book-a-table" href="{% url 'reservation:reservation' %}">Book a Table</a>
        <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
        <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
</header><!-- End Header -->
{% include "layouts/alert.html" with form=form %}


<main id="main">

{% block content %}

{% endblock %}

</main>
</body>
<!-- Vendor JS Files -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'vendor/aos/aos.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
<script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
<script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'vendor/php-email-form/validate.js' %}"></script>


<!-- Template Main JS File -->
<script src="{% static 'js/main.js' %}"></script>


</html>