home/urls.py
from django.urls import path
from .views import HomeView, AboutUsView, ContactUsView, ChefUsView, GalleryView, EventsView

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('contact-us/', ContactUsView.as_view(), name='contact_us'),
    path('our-chefs/', ChefUsView.as_view(), name='our_chefs'),
    path('galleries/', GalleryView.as_view(), name='galleries'),
    path('our-events/', EventsView.as_view(), name='our_events'),

]

menu/urls.py
from django.urls import path
from .views import MenuListView, BarListView, HookahListView, BarCategoryDetailView

app_name = 'menu'

urlpatterns = [
    path("", MenuListView.as_view(), name="menu_items"),
    path("bar-items/", BarListView.as_view(), name="bar_items"),
    path("hookahs/", HookahListView.as_view(), name="hookahs"),
    path('bar-items/<int:pk>/', BarCategoryDetailView.as_view(), name='bar_item_detail'),
]

mysticcloud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('users.urls', namespace='users')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
    path("change-password/", auth_views.PasswordChangeView.as_view()),
    path("reset-password/", auth_views.PasswordResetView.as_view(), name="reset_password"),
    path("password-reset-done/", auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/models.py
from django.db import models

from helpers.media_upload import upload_menu_item_images, upload_bar_item_images


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class BarCategory(models.Model):
    name = models.CharField(max_length=250)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='bar_category_items')

    def __str__(self):
        return self.name


class MenuItem(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to=upload_menu_item_images, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
                                 related_name='menu_items')

    def __str__(self):
        return self.name


class BarItem(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to=upload_bar_item_images, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(BarCategory, on_delete=models.CASCADE,
                                 related_name='bar_items')

    def __str__(self):
        return self.name


class Hookah(models.Model):
    name = models.CharField(max_length=150)
    price = models.FloatField()

    def __str__(self):
        return self.name

menu/forms.py
from django import forms
from .models import MenuItem, BarItem, Category


class MenuItemForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        owner = kwargs.pop("owner") if kwargs.get("owner") else None
        super().__init__(*args, **kwargs)
        if owner:
            self.fields["category"].queryset = Category.objects.filter(owner=owner)

    class Meta:
        model = MenuItem
        fields = ("name", "price", "description",
                  "image", "restaurant")


class BarItemForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        owner = kwargs.pop("owner") if kwargs.get("owner") else None
        super().__init__(*args, **kwargs)
        if owner:
            self.fields["category"].queryset = Category.objects.filter(owner=owner)

    class Meta:
        model = BarItem
        fields = ("name", "price", "description",
                  "image", "restaurant")


class CategoryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["creation_date"].widget.attrs.update(
            {"class": "form-control"})

    class Meta:
        model = Category
        fields = ("name",)

menu/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import DetailView, ListView
from .models import Category, BarItem, BarCategory, Hookah


class MenuListView(ListView):
    template_name = "menu/menu.html"
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.prefetch_related("menu_items", "bar_category_items").all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bar_categories'] = BarCategory.objects.all()
        return context


class BarListView(ListView):
    template_name = "menu/menu.html"
    context_object_name = 'bar_categories'

    def get_queryset(self):
        return BarCategory.objects.prefetch_related("bar_items").all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class HookahListView(View):
    template_name = "menu/hookah.html"

    def get(self, request, *args, **kwargs):
        hookahs = Hookah.objects.all()
        context = {
            "hookahs": hookahs,
        }
        return render(request, self.template_name, context)


class BarCategoryDetailView(DetailView):
    model = BarCategory
    template_name = "menu/bar_item_detail.html"
    context_object_name = "bar_item_detail"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bar_items'] = self.object.bar_items.all()
        return context


class BarItemDetailView(DetailView):
    model = BarItem
    template_name = "menu/bar_item_detail.html"
    context_object_name = "bar_item_detail"

templates/menu/bar_item_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<br>

<body>

<section id="menu" class="menu">
    <div class="container" data-aos="fade-up">

        <div class="section-header">
            <h2>Our Menu</h2>
            <p>Check Our <span>MysticCloud Menu</span></p>
        </div>

        <div class="row">
            {% for item in bar_items %}
                <div class="col-md-4 mb-4">
                    <div class="item-card">
                        <img src="{% if item.image %}{{ item.image.url }}{% else %}
                            {% static 'img/no_image.jpg' %}{% endif %}" alt="{{ item.name }}" class="item-img img-fluid">
                        <div class="item-details">
                            <br>
                            <h3>{{ item.name }}</h3>
                            <br>
                            <h4 class="item-price">{{ item.price }} Amd</h4>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- "Go Back" button -->
        <div class="text-center mt-4">
            <a href="{% url 'menu:menu_items' %}" class="btn btn-primary">Go Back</a>
        </div>

    </div>
</section>

</body>
{% endblock %}

templates/menu/hookah.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<br>
<br>
<br>

<html lang="en">

<body>

<section id="menu" class="menu">
    <div class="container" data-aos="fade-up">

        <div class="section-header">
            <h2>Our Hookahs</h2>
            <p>See Our <span>Hookahs List</span></p>
        </div>

        <div class="row">
            <div class="col-md-8 mx-auto">
                <div class="table-responsive">
                    <!-- Add a class to the table -->
                    <table class="table table-striped light-table">
                        <thead class="thead-dark">
                            <tr>
                                <th>Name</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for hookah in hookahs %}
                                <tr>
                                    <td><h4>{{ hookah.name }}</h4></td>
                                    <td><h4>{{ hookah.price }} Amd</h4></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>
</section>

{% endblock %}

templates/menu/menu.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<br>


<html lang="en">

<body>

<section id="menu" class="menu">
    <div class="container" data-aos="fade-up">

        <div class="section-header">
            <h2>Our Menu</h2>

            <p>Check Our <span>MysticCloud Menu</span></p>
        </div>

        <ul class="nav nav-tabs d-flex justify-content-center" data-aos="fade-up" data-aos-delay="200">
            {% for category in categories %}
            <li class="nav-item">
                <a class="nav-link {% if forloop.first %}active show{% endif %}" data-bs-toggle="tab"
                   data-bs-target="#menu-{{ category.name|lower }}">
                    <h4>{{ category.name }}</h4>
                </a>
            </li><!-- End tab nav item -->
            {% endfor %}
        </ul>

        <div class="tab-content" data-aos="fade-up" data-aos-delay="300">

            {% for category in categories %}
            <div class="tab-pane fade " id="menu-{{ category.name|lower }}">

                <div class="tab-header text-center">
                    <p>Menu</p>
                    <h3>{{ category.name }}</h3>
                </div>

                <div class="row gy-5">
                    {% for item in category.menu_items.all %}
                    <div class="col-lg-4 menu-item">
                        <a href="{{ item.image.url }}" class="glightbox">
                            <img src="{% if item.image %}{{ item.image.url }}{% else %}
                                {% static 'img/no_image.jpg' %}{% endif %}"
                                 class="menu-img img-fluid" alt="{{ item.name }}">
                        </a>
                        <h4>{{ item.name }}</h4>
                        <p class="ingredients">{{ item.description }}</p>
                        <p class="price">{{ item.price }} Amd</p>
                    </div><!-- Menu Item -->
                    {% endfor %}

                    <!-- Display bar items for "Bar" category -->
                  {% if category.name == "Bar" %}
                    {% for item in bar_categories %}
                   <div class="col-lg-4 menu-item">
                        <h3>
                            <a href="{% url 'menu:bar_item_detail' pk=item.pk %}" class="btn btn-link menu-btn">
                                <button class="btn btn-link menu-btn"><h3>{{ item.name }}</h3></button>
                            </a>
                        </h3>
                    </div>
                    <!-- Bar Menu Item -->
                    {% endfor %}
                  {% endif %}

                </div>
            </div><!-- End Menu Content -->
            {% endfor %}

        </div>

    </div>
</section><!-- End Menu Section -->

</body>

{% endblock %}