home/urls.py
from django.urls import path
from .views import HomeView, AboutUsView, ContactUsView, ChefUsView, GalleryView, EventsView

app_name = "home"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('contact-us/', ContactUsView.as_view(), name='contact_us'),
    path('our-chefs/', ChefUsView.as_view(), name='our_chefs'),
    path('galleries/', GalleryView.as_view(), name='galleries'),
    path('our-events/', EventsView.as_view(), name='our_events'),

]

mysticcloud/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('menu/', include('menu.urls', namespace='menu')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('users.urls', namespace='users')),
    path('reservation/', include('reservation.urls', namespace='reservation')),
    path("change-password/", auth_views.PasswordChangeView.as_view()),
    path("reset-password/", auth_views.PasswordResetView.as_view(), name="reset_password"),
    path("password-reset-done/", auth_views.PasswordResetDoneView.as_view(),
         name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(),
         name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(),
         name="password_reset_complete"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from .views import MakeReservationView, cancel_reservation, AllReservationsView

app_name = "reservation"

urlpatterns = [
    path('reservation/', MakeReservationView.as_view(), name='reservation'),
    path('view-reservations/', AllReservationsView.as_view(), name='view_reservations'),
    path('cancel-reservation/<int:reservation_id>/', cancel_reservation, name='cancel_reservation'),
]

users/urls.py
from django.urls import path
from .views import LoginView, RegistrationView, ValidateUserLink, LogoutView, UserUpdate, UserProfile

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registration/", RegistrationView.as_view(), name="registration"),
    path("<int:pk>/<str:token>/", ValidateUserLink.as_view(), name="verify"),
    path("update-user/<int:pk>/", UserUpdate.as_view(), name="update_user"),
    path('users/detail/<int:pk>/', UserProfile.as_view(), name='user_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save
from django.dispatch import receiver
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from helpers.media_upload import upload_user_images


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValidationError("email is required")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None, **extra_fields):
        user = self.create_user(email, password, **extra_fields)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=155, blank=True, null=True)
    last_name = models.CharField(max_length=155, blank=True, null=True)
    image = models.ImageField(upload_to=upload_user_images, blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = UserManager()
    USERNAME_FIELD = "email"

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=upload_user_images, blank=True, null=True)
    country = CountryField(blank=True, null=True)
    phone_field = PhoneNumberField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"


@receiver(post_save, sender=User)
def profile_post_save(instance, created, **kwargs):
    if created:
        profile = Profile(user=instance)
        profile.save()

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django_countries.fields import CountryField
from phonenumber_field.formfields import PhoneNumberField

User = get_user_model()


class EmailForm(forms.Form):
    email = forms.EmailField()
    subject = forms.CharField()
    body = forms.CharField(widget=forms.Textarea())


class RegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "password1", "password2")


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].required = True

    country = CountryField().formfield()
    phone_number = PhoneNumberField(required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "country", "email",
                  "phone_number", "image")

users/views.py
from django.contrib import messages
from .mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView
from django.contrib.auth.views import LoginView as Login
from django.conf import settings
from .forms import RegistrationForm, ProfileForm
from django.contrib.auth import get_user_model, logout
from django.shortcuts import redirect
from django.http import HttpResponse
from .generate_token import account_activation_token

User = get_user_model()


class RegistrationView(CreateView):
    form_class = RegistrationForm
    model = User
    success_url = '/'

    def form_valid(self, form):
        response = super().form_valid(form)
        subject = "Authenticate your Profile"
        user = self.object
        user.is_active = False
        user.save()
        token = account_activation_token.make_token(user)
        message = render_to_string("users/authentication.html",
                                   {"users": user,
                                    "domain": get_current_site(self.request),
                                    "token": token,
                                    "user_pk": user.pk})
        email = EmailMessage(subject=subject, body=message,
                             from_email=settings.EMAIL_HOST_USER,
                             to=[user.email])
        email.send(fail_silently=False)
        messages.success(self.request, "We have sent a link to your email address,"
                                       " please check it to complete the registration")
        return response


class ValidateUserLink(TemplateView):

    def get(self, request, *args, **kwargs):
        token = kwargs.get("token")
        pk = kwargs.get("pk")
        user = User.objects.get(pk=pk)
        if account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            return redirect("users:login")
        return HttpResponse("Your token is invalid")


class LoginView(Login):
    pass


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse('home:home'))


class PasswordChangeDoneView(TemplateView):

    def get(self, request, **kwargs):
        messages.success(request, "Password changed successfully!")
        return redirect("users:user_profile")


class UserProfile(LoginRequiredMixin, DetailView):
    model = User
    template_name = "users/user_profile.html"


class UserUpdate(LoginRequiredMixin, UpdateView):
    model = User
    form_class = ProfileForm

    def get_success_url(self):
        messages.info(self.request, "User updated successfully!")
        return reverse("users:update_profile", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        result = super().form_valid(form)
        self.object.profile.country = form.cleaned_data["country"]
        self.object.profile.phone_number = form.cleaned_data["phone_number"]
        self.object.profile.image = form.cleaned_data["image"]
        self.object.profile.save()
        return result

templates/users/authentication.html
{% autoescape off %}

Congratulations

Please follow the link to complete your registration

http://{{ domain }}/{{ user_pk }}/{{ token }}

{% endautoescape %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

<br>
<br>
<br>
<br>
<br>
<br>
{% block content %}
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-grid gap-2">
                <button class="btn btn-success" type="Submit">Update</button>
            </div>
        </form>
    </div>

{% endblock %}

templates/users/user_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
        <button type="submit" class="brn btn-success">Register</button>
        </form>
    </div>
{% endblock %}

templates/users/user_profile.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
    <link rel="stylesheet" href="{% static "css/profile.css" %}">
    <div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
        <div class="card p-4">
            <div class=" image d-flex flex-column justify-content-center align-items-center">
                <button class="btn btn-secondary">{% if object.profile.image %}<img src="{{ object.profile.image.url }}" height="100" width="100" alt="">
                {% else %}<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ68D1zB62HiAWZAkQpessCgGpmfvJQUX8Rhg&usqp=CAU" height="100" width="100"/>{% endif %}
                </button>
                <span class="name mt-3">{{ object.first_name }} {{ object.last_name }}</span> <span class="idd">{{ object.email }}</span>
                <div class="d-flex flex-row justify-content-center align-items-center gap-2"><span class="idd1">{{ object.profile.phone_number }}</span>
                    <span><i class="fa fa-copy"></i></span></div>
                {% if request.user.reservations.all %}
                <div class="d-flex flex-row justify-content-center align-items-center mt-3"><a href="{% url "reservation:view_reservations" %}"><span
                        class="number">Reservations <span class="number">{{user.reservations.all|length}}</span></a></span></div>
                {% else %}
                <div class="d-flex flex-row justify-content-center align-items-center mt-3"><span
                        class="number">You don't have a <span class="number">Reservations</span></span></div>
                {% endif %}
                <div class=" d-flex mt-2">
                    <a href="{% url "users:update_user" object.pk %}"><button class="btn1 btn-dark">Edite Profile</button></a>
                </div>
                <div class="text mt-3"><span>Country {{ object.profile.country.name }}<br><br> </span>
                </div>
                <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"><span><i
                        class="fa fa-twitter"></i></span> <span><i class="fa fa-facebook-f"></i></span> <span><i
                        class="fa fa-instagram"></i></span> <span><i class="fa fa-linkedin"></i></span></div>
            </div>
        </div>
    </div>
{% endblock %}